name: PHPStan Static Analysis

on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2, cs2pr
          coverage: none
        env:
          update: true

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Execute PHPStan
        run: vendor/bin/phpstan analyze --error-format=checkstyle --no-progress | cs2pr
