name: Test Suite
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ["8.1", "8.2", "8.3", "8.4"]
                composer-flags: [""]
                include:
                    - php: "8.4"
                      composer-flags: "--prefer-lowest"
        name: PHP ${{ matrix.php }} ${{ matrix.composer-flags }} Unit Test
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
            - name: Install Dependencies
              uses: nick-invision/retry@v2
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: composer update ${{ matrix.composer-flags }}
            - name: Run Script
              run: vendor/bin/phpunit
